// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChYvf3cmAJnMJ2De5ExSuXX2XrEi3-WQE',
    appId: '1:411348856306:web:1e5ed67fc7dab7467ecf6b',
    messagingSenderId: '411348856306',
    projectId: 'engkids-ee926',
    authDomain: 'engkids-ee926.firebaseapp.com',
    storageBucket: 'engkids-ee926.firebasestorage.app',
    measurementId: 'G-E2Q0PY0N52',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUsTTEPqdM_fsgdLGHBIoI1yoHJGlror0',
    appId: '1:411348856306:android:afd9fcfd100fc2847ecf6b',
    messagingSenderId: '411348856306',
    projectId: 'engkids-ee926',
    storageBucket: 'engkids-ee926.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0zR1zTXE8-jaMj_02s4-kSgwxZw91WY8',
    appId: '1:411348856306:ios:89e6bbd83be6ba417ecf6b',
    messagingSenderId: '411348856306',
    projectId: 'engkids-ee926',
    storageBucket: 'engkids-ee926.firebasestorage.app',
    iosClientId: '411348856306-ov71vrpv3uag0gt7vud0fbobvc6uhcis.apps.googleusercontent.com',
    iosBundleId: 'com.example.engkids',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0zR1zTXE8-jaMj_02s4-kSgwxZw91WY8',
    appId: '1:411348856306:ios:89e6bbd83be6ba417ecf6b',
    messagingSenderId: '411348856306',
    projectId: 'engkids-ee926',
    storageBucket: 'engkids-ee926.firebasestorage.app',
    iosClientId: '411348856306-ov71vrpv3uag0gt7vud0fbobvc6uhcis.apps.googleusercontent.com',
    iosBundleId: 'com.example.engkids',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChYvf3cmAJnMJ2De5ExSuXX2XrEi3-WQE',
    appId: '1:411348856306:web:d326cd1f1aa3d4747ecf6b',
    messagingSenderId: '411348856306',
    projectId: 'engkids-ee926',
    authDomain: 'engkids-ee926.firebaseapp.com',
    storageBucket: 'engkids-ee926.firebasestorage.app',
    measurementId: 'G-Q1523VYEG2',
  );

}